# This docker-compose is meant for local development.
# It should not be used in production.

version: "3"
services:
  teloal-mongo:
    image: mongo:7
    container_name: teloal-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-user
      MONGO_INITDB_ROOT_PASSWORD: mongo-password
    command: --port 27027
    ports:
      - "27027:27027"
    volumes:
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  teloal-mongo-express:
    image: mongo-express:1.0.0-18-alpine3.18
    container_name: teloal-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ""
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo-user
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo-password
      ME_CONFIG_SITE_COOKIESECRET: teloal-cookie-secret
      ME_CONFIG_SITE_SESSIONSECRET: teloal-session-secret
      ME_CONFIG_MONGODB_URL: mongodb://mongo-user:mongo-password@teloal-mongo:27027/
      ME_CONFIG_OPTIONS_EDITORTHEME: dracula
    ports:
      - "127.0.0.1:7937:8081"
