name: Orchestrates sub-workflows

on: push

jobs:
  lint-all:
    uses: ./.github/workflows/lint.yml

  test-all:
    uses: ./.github/workflows/test.yml

  build-api:
    needs:
      - lint-all
      - test-all
    uses: ./.github/workflows/build.yml
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
