name: Test repository

on: workflow_call

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 18
          cache: "npm"

      - run: npm ci --prefer-offline

      - name: Test all NX packages
        run: npx nx run-many -t test
